channels:
  - defaults
  - conda-forge
dependencies:
  - numpy=1.23.1
  - pip=21.3.1
  - python=3.10
  - scipy=1.9.3
  - scikit-learn=1.1.3
  - mdanalysis=2.6.1
  - pip:
      - matplotlib==3.8.2
      - pyblock==0.6
      - git+https://github.com/bjmorgan/kinisi.git@with-f