channels:
  - defaults
  - conda-forge
dependencies:
  - numpy=1.23.1
  - pip=21.3.1
  - python=3.10
  - scipy=1.9.3
  - scikit-learn=1.1.3
  - mdanalysis=2.3.0
  - pip:
      - git+https://github.com/matplotlib/matplotlib.git
      - pyblock==0.6
      - statsmodels==0.14.0
      - git+https://github.com/bjmorgan/kinisi.git@block
