channels:
  - defaults
  - conda-forge
dependencies:
  - numpy=1.23.1
  - pip=21.3.1
  - python=3.9.7
  - scipy=1.9.3
  - scikit-learn=1.1.3
  - mdanalysis=2.3.0
  - pip:
      - git+https://github.com/matplotlib/matplotlib.git
      - dynesty==1.0.1
      - uravu==1.2.9
      - kinisi==0.6.3
